import { useState, useEffect } from 'react'

function KnowledgeView(): React.JSX.Element {
  const [prompt, setPrompt] = useState<string>('')
  const [unfedCount, setUnfedCount] = useState<number>(0)
  const [totalCount, setTotalCount] = useState<number>(0)
  const [loadingAnalyze, setLoadingAnalyze] = useState<boolean>(false)
  const [loadingReanalyze, setLoadingReanalyze] = useState<boolean>(false)
  const [error, setError] = useState<string | null>(null)
  const [lastResult, setLastResult] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false
    async function load(): Promise<void> {
      try {
        const [{ prompt: p }, unfed, all] = await Promise.all([
          window.api.kbLoadPrompt(),
          window.api.listUnfedConversations(),
          window.api.listConversations()
        ])
        if (!cancelled) {
          setPrompt(p)
          setUnfedCount(unfed.length)
          setTotalCount(all.length)
        }
      } catch {
        // ignore
      }
    }
    load()
    return () => {
      cancelled = true
    }
  }, [])

  const refreshCounts = async (): Promise<void> => {
    const [unfed, all] = await Promise.all([
      window.api.listUnfedConversations(),
      window.api.listConversations()
    ])
    setUnfedCount(unfed.length)
    setTotalCount(all.length)
  }

  const handleAnalyze = async (): Promise<void> => {
    setLoadingAnalyze(true)
    setError(null)
    setLastResult(null)
    try {
      const result = await window.api.kbAnalyze()
      setPrompt(result.newPrompt)
      if (result.conversationsAnalyzed === 0) {
        setLastResult('No unfed conversations to analyze.')
      } else {
        setLastResult(`Analyzed ${result.conversationsAnalyzed} conversation(s).`)
      }
      await refreshCounts()
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err))
    } finally {
      setLoadingAnalyze(false)
    }
  }

  const handleReanalyze = async (): Promise<void> => {
    setLoadingReanalyze(true)
    setError(null)
    setLastResult(null)
    try {
      const result = await window.api.kbReanalyze()
      setPrompt(result.newPrompt)
      if (result.conversationsAnalyzed === 0) {
        setLastResult('No conversations found.')
      } else {
        setLastResult(`Re-analyzed ${result.conversationsAnalyzed} conversation(s).`)
      }
      await refreshCounts()
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err))
    } finally {
      setLoadingReanalyze(false)
    }
  }

  const busy = loadingAnalyze || loadingReanalyze

  return (
    <div className="view-shell">
      <div className="view-shell-header">
        <h1>Knowledge Base</h1>
      </div>
      <div className="view-shell-content">
        <div className="kb-status-bar">
          <span className="kb-status-text">
            {unfedCount > 0
              ? `${unfedCount} unfed conversation(s) ready for analysis`
              : 'All conversations analyzed'}
          </span>
          <div className="kb-buttons">
            <button
              className="settings-header-save"
              disabled={busy || unfedCount === 0}
              onClick={handleAnalyze}
            >
              {loadingAnalyze ? 'Analyzing...' : 'Analyze'}
            </button>
            <button
              className="settings-header-save"
              disabled={busy || totalCount === 0}
              onClick={handleReanalyze}
            >
              {loadingReanalyze ? 'Re-analyzing...' : 'Re-Analyze All'}
            </button>
          </div>
        </div>

        {error && <p className="kb-error">{error}</p>}
        {lastResult && <p className="kb-result">{lastResult}</p>}

        <div className="kb-section">
          <h3 className="settings-section-title">Personalized Lookup Prompt</h3>
          <p className="kb-section-desc">
            Generated by the Knowledge Base Maintenance model from your conversation history.
          </p>
          <textarea
            className="settings-input kb-prompt-textarea"
            value={prompt}
            readOnly
            rows={12}
            placeholder="Run analysis to generate a personalized system prompt..."
            spellCheck={false}
          />
        </div>
      </div>
    </div>
  )
}

export default KnowledgeView
